name: Themegit
description: An opinionated workflow for continuously previewing and deploying Shopify themes
inputs:
  BUILT_THEME_DIR:
    description: The path to your (pre-built) Shopify Theme
    required: true
    default: '.'
  SHOPIFY_STORE_DOMAIN:
    description: Your Shopify store domain
    required: true
  SHOPIFY_PASSWORD:
    description: The same Shopify password you use with Themekit locally
    required: true
  CONFIG_CONFLICT_STRATEGY:
    description: The path to your (pre-built) Shopify Theme
    required: true
    default: 'raise'
  LOCALE_CONFLICT_STRATEGY:
    description: The path to your (pre-built) Shopify Theme
    required: true
    default: 'raise'
  PINNED_BRANCHES:
    description: When set, merging or pushing into these branches will deploy immutable theme versions for managing rolling deployments
outputs:
  SHOPIFY_THEME_PREVIEW_URL:
    description: 'The preview URL for Shopify'
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.BUILT_THEME_DIR }}
    - ${{ inputs.SHOPIFY_STORE_DOMAIN }}
    - ${{ inputs.SHOPIFY_PASSWORD }}
    - ${{ inputs.CONFIG_CONFLICT_STRATEGY }}
    - ${{ inputs.LOCALE_CONFLICT_STRATEGY }}
    - ${{ inputs.PINNED_BRANCHES }}
